// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9qFNB_r6esCCRQwohRdNOgZkjYH35uVI',
    appId: '1:20241355031:web:55bfceb272606ce57aa752',
    messagingSenderId: '20241355031',
    projectId: 'rxdart-course-jhw',
    authDomain: 'rxdart-course-jhw.firebaseapp.com',
    storageBucket: 'rxdart-course-jhw.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg13RTq4uAwsHC3v6rD9_0LJez87_7G7o',
    appId: '1:20241355031:android:fe7975bca53906147aa752',
    messagingSenderId: '20241355031',
    projectId: 'rxdart-course-jhw',
    storageBucket: 'rxdart-course-jhw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoXqa3VxefYPymi78Fy1gRWJamOqjPJo4',
    appId: '1:20241355031:ios:0b49b1fa34d9f3bd7aa752',
    messagingSenderId: '20241355031',
    projectId: 'rxdart-course-jhw',
    storageBucket: 'rxdart-course-jhw.appspot.com',
    iosBundleId: 'dev.hjia.rxdartCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoXqa3VxefYPymi78Fy1gRWJamOqjPJo4',
    appId: '1:20241355031:ios:233524107d2f3cf37aa752',
    messagingSenderId: '20241355031',
    projectId: 'rxdart-course-jhw',
    storageBucket: 'rxdart-course-jhw.appspot.com',
    iosBundleId: 'dev.hjia.rxdartCourse.RunnerTests',
  );
}
